name: Run Gmail Labeler

on:
  schedule:
    # 07:00 y 15:00 UTC diario
    - cron: '0 7 * * *'
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  run-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend deps
        run: |
          cd backend
          npm ci

      - name: Restore credentials.json
        run: |
          printf '%s' "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > backend/credentials.json

      - name: Restore token.json (optional)
        run: |
          if [ -n "${{ secrets.GMAIL_TOKEN_JSON_B64 }}" ]; then
            echo "${{ secrets.GMAIL_TOKEN_JSON_B64 }}" \
            | base64 --decode > backend/token.json
          fi

      - name: Run labeler
        working-directory: backend
        run: npm run label
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          REDIRECT_URI:     ${{ secrets.REDIRECT_URI }}
          SESSION_SECRET:   ${{ secrets.SESSION_SECRET }}
